# Define o perfil (dev ou prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- BANCO DE DADOS (A Mágica Híbrida) ---
# Se tiver a variável SPRING_DATASOURCE_URL (Nuvem), usa ela.
# Se não tiver, usa o localhost (Seu PC).
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/mini_ecommerce}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- SEGURANÇA ---
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration-hours=2
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}