CREATE TABLE tb_interest_signup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(30),
    interest_type VARCHAR(20) NOT NULL,
    interest_reference VARCHAR(255),
    message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);
