CREATE TABLE tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority VARCHAR(255)
);

CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255)
);

CREATE TABLE tb_user_role (
    user_id BIGINT,
    role_id BIGINT,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES tb_user(id),
    FOREIGN KEY (role_id) REFERENCES tb_role(id)
);

CREATE TABLE tb_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE tb_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    price DECIMAL(19, 2),
    img_url VARCHAR(255)
);

CREATE TABLE tb_product_category (
    product_id BIGINT,
    category_id BIGINT,
    PRIMARY KEY (product_id, category_id),
    FOREIGN KEY (product_id) REFERENCES tb_product(id),
    FOREIGN KEY (category_id) REFERENCES tb_category(id)
);

CREATE TABLE tb_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE tb_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment TIMESTAMP WITHOUT TIME ZONE,
    order_status VARCHAR(255),
    client_id BIGINT,
    FOREIGN KEY (client_id) REFERENCES tb_client(id)
);

CREATE TABLE tb_order_item (
    order_id BIGINT,
    product_id BIGINT,
    quantity INTEGER,
    price DECIMAL(19, 2),
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES tb_order(id),
    FOREIGN KEY (product_id) REFERENCES tb_product(id)
);

-- Inserindo os papéis (roles) iniciais
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (authority) VALUES ('ROLE_CLIENT');